# Generated by Django 2.1.2 on 2018-11-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20181117_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None,
                                       verbose_name='deleted_at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True,
                                       verbose_name='created_at'),
        ),
        migrations.RunSQL(
            'ALTER TABLE users MODIFY COLUMN deleted_at \
            DATETIME AFTER current_login_at')

    ]
