version: '3.3'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_USER: cola
      MYSQL_PASSWORD: qwer1234
      MYSQL_DATABASE: flatcoke
    ports:
      - 3306:3306

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A flatcoke worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A flatcoke beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  flower:
    image: mher/flower
    command: ["flower", "--broker=redis://redis:6379/0", "--port=8888"]
    ports:
       - 8888:8888

  app:
    build: .
    restart: always
    volumes:
      - .:/www/server
    links:
    - db
    - redis
    depends_on:
    - db
    - redis
    env_file: .env
    environment:
    - C_FORCE_ROOT=true
    command: >
      bash -c "sh run_uwsgi.sh"
    ports:
      - "8000:8000"

volumes:
  dbdata:
